name: Post-merge

on:
  push:
    branches:
      - main
      - 'release/**'
  workflow_dispatch:
    inputs:
      scope:
        description: 'Select which component of the version should be incremented'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch
      stage:
        description: 'Select which stage of the release should be published'
        required: true
        default: 'snapshot'
        type: choice
        options:
          - final
          - snapshot

jobs:
  build:
    uses: kyhule/polyworld-workflows/.github/workflows/post-merge.yml@9da5c4ddc40a2c2a0884a2d8f09136dc7d037f33
    secrets: inherit
    with:
      version-scope: ${{ inputs.scope || vars.SCOPE }}
      version-stage: ${{ inputs.stage || vars.STAGE }}
      setup-android: false
