name: Pull Request

on:
  pull_request:
  merge_group:

jobs:
  build:
    uses: kyhule/polyworld-workflows/.github/workflows/pre-merge.yml@9b3a29e80ac7e384885fdfaeee2d6979e47f962f
    secrets: inherit
    with:
      setup-android: false
