name: Pull Request

on:
  pull_request:
    paths-ignore:
      - '*.md'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false

jobs:
  build:
    uses: kyhule/polyworld-workflows/.github/workflows/pre-merge.yml@9da5c4ddc40a2c2a0884a2d8f09136dc7d037f33
    secrets: inherit
    with:
      setup-android: false
